<a href="https://colab.research.google.com/github/Sunay-2103/SunayMukherjee_23FE10CSE00636/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [4]:
seed_data_df = pd.read_csv('/content/Seed_Data.csv')
display(seed_data_df.head())

,A,P,C,LK,WK,A_Coef,LKG,target
0,15.26,14.84,0.8710,5.763,3.312,2.221,5.220,0
1,14.88,14.57,0.8811,5.554,3.333,1.018,4.956,0
2,14.29,14.09,0.9050,5.291,3.337,2.699,4.825,0
3,13.84,13.94,0.8955,5.324,3.379,2.259,4.805,0
4,16.14,14.99,0.9034,5.658,3.562,1.355,5.175,0


In [7]:
print(seed_data_df['A'])

0      15.26
1      14.88
2      14.29
3      13.84
4      16.14
       ...  
205    12.19
206    11.23
207    13.20
208    11.84
209    12.30
Name: A, Length: 210, dtype: float64


In [8]:
seed_data_df['target']

,target
0,0
1,0
2,0
3,0
4,0
...,...
205,2
206,2
207,2
208,2


In [13]:
# Define a dataframe with only features
df_feat = seed_data_df.drop('target',axis=1)
display(df_feat.head())

,A,P,C,LK,WK,A_Coef,LKG
0,15.26,14.84,0.8710,5.763,3.312,2.221,5.220
1,14.88,14.57,0.8811,5.554,3.333,1.018,4.956
2,14.29,14.09,0.9050,5.291,3.337,2.699,4.825
3,13.84,13.94,0.8955,5.324,3.379,2.259,4.805
4,16.14,14.99,0.9034,5.658,3.562,1.355,5.175


In [14]:
df_target = seed_data_df['target']
display(df_target.head())

,target
0,0
1,0
2,0
3,0
4,0


In [11]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(df_feat, df_target, test_size=0.30, random_state=101)

In [16]:
from sklearn.svm import SVC

In [19]:
model = SVC()

In [20]:
model.fit(X_train,y_train)

SVC()

In [21]:
predictions = model.predict(X_test)

In [24]:
from sklearn.metrics import classification_report,confusion_matrix

In [25]:
print(confusion_matrix(y_test,predictions))


[[20  3  3]
 [ 0 15  0]
 [ 0  0 22]]


In [26]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      0.77      0.87        26
           1       0.83      1.00      0.91        15
           2       0.88      1.00      0.94        22

    accuracy                           0.90        63
   macro avg       0.90      0.92      0.90        63
weighted avg       0.92      0.90      0.90        63



In [27]:
print("Misclassification error rate:",
      round(np.mean(predictions!=y_test),3))

Misclassification error rate: 0.095


In [32]:
param_grid = {'C': [0.1,1, 10, 100, 1000],
              'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']}

In [29]:
from sklearn.model_selection import GridSearchCV


In [30]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=1)

In [33]:

grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits


GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=1)

In [34]:
grid.best_params_

{'C': 100, 'gamma': 0.1, 'kernel': 'rbf'}

In [35]:
grid.best_estimator_

SVC(C=100, gamma=0.1)

In [36]:
grid_predictions = grid.predict(X_test)

In [37]:
print(confusion_matrix(y_test,grid_predictions))


[[21  3  2]
 [ 0 15  0]
 [ 0  0 22]]


In [38]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

           0       1.00      0.81      0.89        26
           1       0.83      1.00      0.91        15
           2       0.92      1.00      0.96        22

    accuracy                           0.92        63
   macro avg       0.92      0.94      0.92        63
weighted avg       0.93      0.92      0.92        63



In [39]:
param_grid = {'C': [50,75,100,125,150], 'gamma': [1e-2,1e-3,1e-4,1e-5,1e-6], 'kernel': ['rbf']}
grid = GridSearchCV(SVC(tol=1e-5),param_grid,refit=True,verbose=1)
grid.fit(X_train,y_train)


Fitting 5 folds for each of 25 candidates, totalling 125 fits


GridSearchCV(estimator=SVC(tol=1e-05),
             param_grid={'C': [50, 75, 100, 125, 150],
                         'gamma': [0.01, 0.001, 0.0001, 1e-05, 1e-06],
                         'kernel': ['rbf']},
             verbose=1)

In [40]:
grid.best_estimator_

SVC(C=75, gamma=0.01, tol=1e-05)

In [41]:
grid_predictions = grid.predict(X_test)
print(confusion_matrix(y_test,grid_predictions))

[[21  3  2]
 [ 0 15  0]
 [ 0  0 22]]
